### ISSUE TITLE
Submit to Homebrew

### ISSUE THREAD

**Issue by snoe** [snoe/clojure-lsp#1]
It would be helpful to get a formula in homebrew

I guess this is the starting point: https://docs.brew.sh/Formula-Cookbook

**Comment by markx** [comment]
Homebrew has a "test" step to verify the installation. How do you think this can be tested?

**Comment by snoe** [comment]
Well, the binary responds to JSON RPC on stdin so if the have a framework around that, sending a supported message on stdin should suffice https://microsoft.github.io/language-server-protocol/specification

**Comment by markx** [comment]
Since the binary blocks on reading stdin and doesn't exit, I think it will have to run in a process, and then we start another process to check the output and stop the binary. This sounds a little too complex to me.

It'll be trivial to test if it can take a flag , like `--help` or `--version`, and output some fixed string. I think this is the case for many interactive programs on homebrew.

**Comment by snoe** [comment]
That makes sense to me.

**Comment by markx** [comment]
I did a little search, and found that most, if not all, lang servers are distributed via the language's own package manager, instead of homebrew. In this way it is automatically available on all platform it supports. Is it possible to do this via leiningen, or something else?

**Comment by snoe** [comment]
Good question.

There's a few exceptions in the list here https://langserver.org#implementations-server I think the main difference is that so many languages now have blessed package managers that can install binaries. 

Clojure now has `clj` maybe we can specify the github repo on the cli and a main to run...

With lein, we'd have to make this into a lein plugin and tell people to add it to their profiles, or do what cider does and inject the plugin from cli... it's doable but will probably get hairy and it excludes people not using lein.

We could probably wrap this in a package.json and distribute with npm which, the world being as it is, would probably be available for most people. 

Some language tools (like lein and npm) do the `curl | sh` approach is an approach that gets people running but has security concerns.

**Comment by snoe** [comment]
I want to enumerate the the problems I'm trying to solve with homebrew:

1) A standard, stable way of launching the server for clients, many of whom will have their own releases. So the command should not change, should not require hard coded paths, and be as close to cross platform as possible. This means we need some executable on the path that can launch the server. (e.g. `clojure-lsp`, `java -m clojure.lsp.main`, etc).

2) Installable - ideally it's one step to get clojure-lsp onto their system and ready to run. No `chmod` step, or downloading and moving to a $PATH.

3) Upgradeable - there should be a straightforward way to get the latest version

4) Manual install should still be possible - if people want to opt out of our release system, or don't have an internet connection they should still be able to run, install, and upgrade manually.

--- 
I looked at clojure CLI tools https://clojure.org/guides/getting_started

This is possibly a valid avenue. 


Users can add to their `~/.clojure/deps.edn` file
```
{:aliases
 {:lsp {:extra-deps {snoe/clojure-lsp {:git/url "https://github.com/snoe/clojure-lsp" :sha "a90836ce5a50147347a55001505cc29bbe171dc1"}}
        :main-opts ["-m" "clojure-lsp.main"]
        :jvm-opts ["-Xmx1g" "-server"]}}}
```

And run with `clojure -A:lsp` 

But...
On macos they get `clojure` through homebrew
On Linux they get it through a `curl | sh`
On windows they get it through a very early release powershell module, and exec it with `powershell -Command "& cojurej -A:lsp"`

I'm also not sure who has the cli tools installed, is it most clojure users? (2019 survey says ~35% of clj and 20% of cljs users use them as a build tool).

So this hits criteria 1, possibly falls short on 2 if most users don't have the tools, and also falls short on 3 since they'd have to go to github, get the latest release sha, and edit their deps.edn in order to upgrade, then for 4 if they go the manual route the clients would either point to our binary or exec `java` directly which means client instructions would diverge, or we provide wrapper scripts so 1 doesn't fall down.

On the other hand, this is probably the easiest to maintain.

**Comment by markx** [comment]
I don't really understand the point of the clojure cli tool. It doesn't want to be the official one-stop shop to replace lein and boot, so I don't know what it's for. Also it uses the strangest argument format I've ever seen, ie the `-A:lsp`.

I was thinking about maybe a lein plugin, which creates a `bin` directory somewhere, and adds a command like `install` that creates jar scripts for executable jars. Users just need to add the `bin` to `PATH` once, similar to how Golang works.

Anyway, if you think homebrew is still suitable, we can still move forward.

**Comment by snoe** [comment]
Heh yeah, I think that's the problem with any build tool, people have their favourites.

So let's continue with homebrew.

**Comment by markx** [comment]
Done.

**Comment by snoe** [comment]
Thank you so much for doing this!
