### ISSUE TITLE
Arity diagnostic does not work on schema.core/defn

### ISSUE THREAD

**Issue by ericdallo** [snoe/clojure-lsp#104]
The arity check diagnotic feature is awesome, but it looks like broke `schema.core/defn` arity check :(
Is too hard to add support for that?

![image](https://user-images.githubusercontent.com/7820865/72526953-5ac5cc80-3846-11ea-8f42-3869935766a2.png)

**Comment by snoe** [comment]
fixed by ef37e7e11154d688c96c2a7ad27c9d4a5b584c03

arity checks are ignored with an `:ignore-arity? true` on the macro def.
Happy to take a pr to somehow produce a signature sexpr that can be checked.
