### ISSUE TITLE
Problems parsing some nested cond-> expressions with custom macros

### ISSUE THREAD

**Issue by Cnly** [snoe/clojure-lsp#105]
I noticed that clojure-lsp isn't able to parse its own `refactor/transform.clj` with the error message `Assert failed: could not create subzipper`. The error is from this line:

https://github.com/snoe/clojure-lsp/blob/ef37e7e11154d688c96c2a7ad27c9d4a5b584c03/src/clojure_lsp/parser.clj#L397

and one short piece of code that seems to cause the parsing problem is:

https://github.com/snoe/clojure-lsp/blob/ef37e7e11154d688c96c2a7ad27c9d4a5b584c03/src/clojure_lsp/refactor/transform.clj#L138-L145

Based on that, I've managed to create a smaller sample:

```clojure
(defmacro my-> [x expr]
    `(~(first expr) ~x ~@(rest expr)))

(-> [1 2 3]
    (my-> (cond-> :always reverse)))
```

**Comment by snoe** [comment]
Thanks for the heads up and the test case.

Fixed by 18a5646 

See how https://github.com/snoe/clojure-lsp/blob/18a5646478a26a44caca99ca47408f2b3cba9543/test/clojure_lsp/parser_test.clj#L573-L576 for a macro-def of a custom threading macro.
