### ISSUE TITLE
FYI Error java.lang.UnsupportedClassVersionError java8

### ISSUE THREAD

**Issue by leandropincini** [snoe/clojure-lsp#114]
Hello, I don't know if someone else is facing this error:
`
$clojure-lsp
Exception in thread "main" java.lang.UnsupportedClassVersionError: clojure_lsp/ClojureExtensions has been compiled by a more recent version of the Java Runtime (class file version 57.0),
 this version of the Java Runtime only recognizes class file versions up to 52.0
`

I'm using Java 8 (Oracle JDK) and installed clojure-lsp with homebrew, using latest version from your github releases repository. [homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/clojure-lsp.rb#L4)

Since I clone the repository and recompile clojure-lsp with java 8 ($lein bin), the problem is gone. 👍

**Comment by achikin** [comment]
Same for me, but my version is 55 instead of 52. I'm using macosx Mojave 10.14.6

**Comment by dcarley** [comment]
It's the Homebrew [bottle](https://docs.brew.sh/Bottles) that compiles against a newer version of Java, rather than the release process in this project. I'm not sure how those binary builds are configured. You can bypass the bottle with:
```
brew install clojure-lsp --build-from-source
```

**Comment by ericdallo** [comment]
Closing it since we already fixed it a long time ago :sweat_smile:
