### ISSUE TITLE
Feature Request: Configurable prefix for user messages

### ISSUE THREAD

**Issue by PEZ** [snoe/clojure-lsp#116]
The problem: Bundling the lsp with Calva will probably be something that most users will get a lot of nice functionality, w/o really knowing anything about clojure-lsp. This is a bit of the case already today with clj-kondo, but my current idea for clojure-lsp is a deeper integration where the functionality is included in the Calva extension. (clj-kondo is separate extension, maintained by @borkdude). So the user facing messages can raise questions about from where they originate. Take this message as an example (from a hover over a symbol in VS Code).

<img width="411" alt="image" src="https://user-images.githubusercontent.com/30010/75864699-b6521680-5e02-11ea-8cdd-dc9685305ab6.png">

It would be good if I could present it as coming from Calva. Never mind the actual example here, I will have to decide if I include the linting help from clojure-lsp, or not. What's important is that I want to be able to configure the messages so that it is clear from where they originate.

**Comment by snoe** [comment]
Yup that makes sense, a PR would be welcome.

**Comment by bpringe** [comment]
FYI this is done by adding `source` to the diagnostics in the `textDocument/publishDiagnostics` response messages. 

I'd think we'd want them to say clojure-lsp and not Calva though, for the ones coming from clojure-lsp, so it's clear they originate from clojure-lsp? You can see the bottom one below says clj-kondo, though this is coming from clj-kondo within clojure-lsp, I didn't have the kondo extension installed.

This image shows another issue though, in that private vars are receiving diagnostics from both clojure-lsp and clj-kondo, which I'm guessing will need to be addressed, or maybe the goal is to remove all diagnostic creation from clojure-lsp?

![image](https://user-images.githubusercontent.com/12722744/101110242-6ec50a80-358d-11eb-8922-3ee33d4e3064.png)

**Comment by ericdallo** [comment]
Yes, as said [here](https://github.com/snoe/clojure-lsp/issues/199#issuecomment-739109778), we should replace `clojure-lsp`'s diagnostics by `clj-kondo` diagnostics, there is a WIP PR [here](https://github.com/snoe/clojure-lsp/pull/176), but it´ s not ready and it's kind of stuck.
Help is very welcome!

**Comment by ericdallo** [comment]
@bpringe this issue seems to be the only one blocking https://github.com/BetterThanTomorrow/calva/issues/868, right?
Do you think adding `clojure-lsp` as the source would be enough?

**Comment by PEZ** [comment]
Yes, I think @bpringe is right. The user is best informed if we surface clojure-lsp as the source for these.

**Comment by ericdallo** [comment]
@PEZ @bpringe added in latest release `clojure-lsp` sources for the only 2 linters we currently have that are not from clojure-lsp, `Unknown forward declaration` and `Unused declaration/ns`.
Let me know if this not work for you :)
