### ISSUE TITLE
Add a way to suppress "unused namespace" warnings

### ISSUE THREAD

**Issue by shepheb** [snoe/clojure-lsp#119]
This commonly happens with integrant or other similar configurations. Most of the user's namespaces aren't required directly by any others. Instead they're referenced in the integrant `config.edn` file and loaded dynamically in the REPL by `(go)`.

That causes all the user namespaces to show up as "unused".

You can work around this by defining an (unused) main somewhere, and having that namespace import the main namespaces of your codebase. But that's far from ideal. I'd rather just turn off the warning altogether, or have a whitelist of namespaces that are always considered as used.

**Comment by snoe** [comment]
Makes sense, I'd gladly take a PR for this.
Configuration that matched kondo's (even if it didn't yet support regexes) would make a lot of sense to me.

https://github.com/borkdude/clj-kondo/blob/master/doc/config.md#exclude-required-but-unused-namespace-from-being-reported

**Comment by ericdallo** [comment]
Closing this since now we use `clj-kondo` which already supports that
