### ISSUE TITLE
Vim guide?

### ISSUE THREAD

**Issue by christianpoveda** [snoe/clojure-lsp#12]
Hey hi!

I've been trying to use clojure-lsp with neovim via LanguageClient-neovim without success.

I've downloaded the standalone binary from the latest release and also i tried to clone and build the binary myself but i cannot get any completions. I had other languages with their own LSP working.

Thank you!!

**Comment by snoe** [comment]
I've noticed this might be broken at the moment but haven't had the time to look into it. I'll try to do that this week.

**Comment by snoe** [comment]
I've put out a new release that touches on a number of issues with completions. 
I've had the best success with LanguageClient-neovim and deoplete in neovim and in VSCode.

If there are still issues, I will need more details; preferably a minimal reproducable sample.

**Comment by patrickpichler** [comment]
I assume you have added the LanguageClient-neovim package alread:
```

let g:LanguageClient_serverCommands = {
    \ 'clojure': ['clojure-lsp'],
\ }
```

I have clojure-lsp in my path. If i try to start the client with `:LanguageClientStart` i get `Failed to start language server (["clojure-lsp"]): Exec format error (os error 8)`

**Comment by patrickpichler** [comment]
Can you maybe post your `g:LanguageClient_serverCommands` part of the vimscript to start the server?

**Comment by snoe** [comment]
@patrickpichler what os are you using?

**Comment by patrickpichler** [comment]
I use Linux

**Comment by patrickpichler** [comment]
I think this issue can be closed :+1:
