### ISSUE TITLE
Support JavaSript interop in ClojureScript

### ISSUE THREAD

**Issue by sfertman** [snoe/clojure-lsp#13]
From http://cljs.info/cheatsheet/ JavaScript interop section

Operation | code
-|-
Create Object | #js {} js-obj
Create Array | #js [] array make-array aclone
Get Property | (.-innerHTML el) <br> Using cljs-oops library: <br> (oget el "innerHTML")
Set Property | (set! (.-innerHTML el) "Hi!") <br> Using cljs-oops library: <br> (oset! el "innerHTML" "Hi!")
Delete Property | js-delete
Convert Between | clj->js js->clj
Type Tests | array? fn? number? object? string?
Exceptions | try catch finally throw
External Library | (js/alert "Hello world!") <br> (js/console.log my-obj) <br> (.html (js/jQuery "#myDiv") "Hi!")

**Comment by snoe** [comment]
A good chunk of this was fixed in 2989b1dc3ff55ed9d488fb461d44f3562d52e93b
As always, there's room for improvements but I'll let new issues guide me on this.
