### ISSUE TITLE
question about completion

### ISSUE THREAD

**Issue by scotts777** [snoe/clojure-lsp#136]
Hi,  I am trying to write an LSP client that uses clojure-lsp.  I am wondering if completion for a function call works with a namespace and/ or an alias?

For example when I try to complete
`clojure.p`
it will send 
`[Trace - 07:18:44 PM] Sending request 'textDocument/completion - (83)'
Params: {
  "context": {
    "triggerKind": 1
  },
  "textDocument": {
    "uri": "file:///Users/sesuler/Projects/Clojure/fiat/src/fiat/money.clj"
  },
  "position": {
    "line": 6,
    "character": 11
  }
}
`
clojure-lsp correctly sends back:
`[Trace - 07:18:44 PM] Received response 'textDocument/completion - (83)' in 12ms
Result: [
  {
    "label": "clojure.parallel",
    "detail": "clojure.parallel"
  },
  {
    "label": "clojure.pprint",
    "detail": "clojure.pprint"
  }
]
`
But if I then choose clojure.pprint and then type a forward slash "/" so that my call looks like
`(clojure.pprint/)` with the cursor right after the slash and before the ")" the completion result is:

`[Trace - 07:23:33 PM] Received response 'textDocument/completion - (93)' in 16ms
Result: [
  {
    "label": "clojure.pprint",
    "detail": "clojure.pprint"
  }
]`
It is as if completion is not seeing the foward slash.  I would expect the response to be the functions in the clojure.pprint namespace.  The same results happen when I us an alias in a function call:
`(pp/)` where "pp" is an alias for clojure.pprint.

Any suggestions would be appreciated as this is my first attempt to write a client.  I am using eclipse lsp but I doubt that is the issue here because the tracing output looks good.

**Comment by ericdallo** [comment]
Confirmed that this happens too with [lsp-mode](https://emacs-lsp.github.io/lsp-mode/page/lsp-clojure/)

**Comment by snoe** [comment]
Thanks for the report. Ok so three issues.
1) I do not provide completion on namespace functions, only aliases. It makes sense to add though.

2) `clojure.pprint` namespace uses `load` to read everything in and clojure-lsp doesn't know how to handle that. So it looks like it's an empty namespace. This might be worth hard coding some entries until `load` is implemented.

3) Parsing for the file fails with an open slash (`string/`) and the internal db only sees the previous edit: (`string`). However on an alias, you should get a completion list at `string` and in coc.nvim at least the completion list stays open as you type the `/`.

For me this works most of the time but fails if I get to `pp/` from the other side with backspace `string/foo` -> `string/` it's a bit clunky but knowing the limitation it's often possible to workaround by going to `string`.

The current behaviour was the best I could think of at the time but there's definitely room for improvement. 

Happy to take PRs on either part.

**Comment by scotts777** [comment]
@snoe thanks for that feedback.  I didn't realize `clojure.pprint` was basically an empty namespace and that was what I was using to test my client.  Yes, I see how it works now by using a normal namespace like `clojure.string`.  
I want to thank you for clojure-lsp and all the hard work you do on it.  It is such a valuable piece to clojure tooling.
