### ISSUE TITLE
Using type/record constructor args when extending doesn't count as usage

### ISSUE THREAD

**Issue by eerohele** [snoe/clojure-lsp#138]
Repro:

```clojure
(defprotocol Baz
  (quux [this]))

(defrecord Foo [bar])

(extend-protocol Baz
  Foo
  (quux [{:keys [bar]}] (inc bar)))
```

Extending the protocol within the `defrecord` body shows `bar` as used, as expected:

```clojure
(defrecord Foo [bar]
  Baz
  (quux [_] bar))
```

Solving this issue is potentially quite difficult, because Clojure has so many ways of extending types. For example, in addition to the `extend-protocol` example above, there are at least:

```clojure
(extend-type Foo
  Baz
  (quux [{:keys [bar]}] (inc bar)))

;; and

(extend Foo
  Baz
  {:quux (fn [{:keys [bar]}] (inc bar))})
```

FWIW, it appears Cursive never shows `deftype`/`defrecord` args as unused, which, I think, is an understandable decision given the circumstances.

**Comment by ericdallo** [comment]
I confirmed this doesn't happen anymore since we use `clj-kondo` for lining now, LMK if any issues

**Comment by eerohele** [comment]
Just checked, looks like this one has indeed been resolved. Thanks!
