### ISSUE TITLE
Exclude unresolved namespaces from being reported?

### ISSUE THREAD

**Issue by FongHou** [snoe/clojure-lsp#139]
Hi,

I think clojure-lsp currently doesn't parse standalone (require ...) forms. Is it worthwhile to add what [clj-kondo](https://github.com/borkdude/clj-kondo/blob/master/doc/config.md#exclude-unresolved-namespaces-from-being-reported) does?

I understand standalone require should be generally discouraged, but sometimes it's useful for repl evaled code in (comment ...). Also, [libpython-clj](https://github.com/clj-python/libpython-clj/blob/b12b8acb672fe22855f6c81c83b04a0d0a2d7000/src/libpython_clj/require.clj#L177) has a similar require-python form that has no equivalent ns clause.

clojure-lsp currently generates lots of noise in quickfix list in both cases, make it harder to spot real issues.

Thanks!

**Comment by ericdallo** [comment]
The `linters` option doen's fix you problem? https://github.com/snoe/clojure-lsp#initializationoptions

**Comment by FongHou** [comment]
linters option  can only ignore unused-namespace (declared in (ns (:require ...)) but not being used by any references. What I described is about other ways to declare namespaces and resolve unknown references.

**Comment by ericdallo** [comment]
@FongHou we now use `clj-kondo` for linting, so it may be available already, let me know if it didn't solve your issue
