### ISSUE TITLE
Running clojure-lsp in command line.

### ISSUE THREAD

**Issue by hifall** [snoe/clojure-lsp#14]
Hi,

I am very new to the Clojure world. When trying to follow the install instructions, I am kinda lost. I have downloaded the clojure-lsp package, and unzipped it. But I can't find any executable for clojure-lsp.

What I am trying to do is to try to start the server from command line, then call it from another process after I've had success.

Could you please provide more detail on how to start the server?

Thanks!

**Comment by pedrorgirardi** [comment]
Hi,

**clojure-lsp** is your executable, but you don't need to run it yourself. The LSP client - VS Code, Vim, or other - will run the server for you. @snoe please correct me if I'm wrong.

Which client are you using? Because basically you just need to have `clojure-lsp` in your PATH with the right permissions - `chmod 755`- and you should be ready to go :)

**Comment by hifall** [comment]
I am using Microsoft's Monaco editor, which is the web version of VS Code.

**Comment by hifall** [comment]
Since there is no instruction on Monaco/clojure-lsp integration, I need to try to run it manually on commandline, so that I can get a basic grasp of it.

**Comment by snoe** [comment]
@hifall The clojure-lsp package in releases is an executable as pedrorgirardi said. 

If you `chmod 755 clojure-lsp && ./clojure-lsp` from the cli you will have an instance of the server running. 

However the server only looks at stdin and puts results to stdout:
https://github.com/snoe/clojure-lsp/blob/9e4ca60e1462c2900e5056622e1061c05edae638/src/clojure_lsp/main.clj#L294

If you need to listen and respond with tcp, I believe the lsp4j library I use supports that and I'd gladly take a PR that allowed you to do that. (This looks like a place to start https://github.com/eclipse/lsp4j/issues/189#issuecomment-413830912 )

Alternatively, I suspect you might be able to hack something with `nc` to pipe in and out to a socket and if you take that route I'd love to hear how it works.

**Comment by hifall** [comment]
I see. Will try out later. Thanks!
