### ISSUE TITLE
Parser does not understand providing an explicit name to defmethod

### ISSUE THREAD

**Issue by thurn** [snoe/clojure-lsp#149]
Clojure multimethod implementations can be given an explicit name, in order to improve stack traces:

`(defmethod foo "a" name-of-method [params] "was a")`

It seems that `clojure-lsp` does not understand this syntax at all, and tries to parse the method name as a parameter list.

**Comment by ericdallo** [comment]
It seems to be a bug on the macro definition: https://github.com/snoe/clojure-lsp/blob/master/src/clojure_lsp/parser.clj#L763

**Comment by ericdallo** [comment]
@thurn this seems to doesn't happen anymore since we now use `clj-kondo` for linting, could you confirm that?
feel free to open the issue otherwise.
