### ISSUE TITLE
Java 11 support

### ISSUE THREAD

**Issue by chenrui333** [snoe/clojure-lsp#155]
I wonder if there is any timeline to support Java 11. Thanks!

**Comment by snoe** [comment]
What specifically are you looking for? @chenrui333

**Comment by chenrui333** [comment]
@snoe 👋 right now I have seen build issue with jdk 8 greater, that is why I raised this issue.

https://github.com/Homebrew/homebrew-core/blob/master/Formula/clojure-lsp.rb#L19-L20

**Comment by snoe** [comment]
So it was building with jdk 11 for awhile and that was fine, unless you had a jdk 8 runtime. I'm not sure how to balance this, any suggestions?

https://github.com/snoe/clojure-lsp/issues/151#event-3493868687

**Comment by chenrui333** [comment]
I will try to build it with jdk11 later today to see if it works. (along with the latest release)

**Comment by ericdallo** [comment]
Closing this since it seems already works, if any issues let me know @chenrui333

**Comment by chenrui333** [comment]
@ericdallo it is still an issue on the build side, I am also adding java 11 into CI to see if it is still an issue. Thanks!

**Comment by chenrui333** [comment]
looks like java 11 and java 15 both work for the CI. 🎉

**Comment by ericdallo** [comment]
Thank you for the PRs :)
