### ISSUE TITLE
Can't get macro defs to work for simple let binding

### ISSUE THREAD

**Issue by socksy** [snoe/clojure-lsp#157]
Hi, in my `.lsp/config.edn` I've put the following:

```clojure
{"macro-defs" {reagent.core/with-let ["bindings" "bound-elements"]}}
```
to try and get reagent's `with-let` to be handled like a normal let. However, while this removes the "undefined" warnings, it seems to completely ignore everything inside the binding, causing lots of unused warnings and no longer recognising any mistakes inside that binding. Am I misunderstanding what `macro-defs` is supposed to do, or have I made a syntax error? (I was trying to follow the documentation in the README)

**Comment by ericdallo** [comment]
@socksy for me it works with:
```clojure
{"macro-defs" {reagent.core/with-let [:bindings :bound-elements]}}
```

![image](https://user-images.githubusercontent.com/7820865/87984368-417d3180-cab0-11ea-85a7-be220615db2a.png)

With unused warning on `b`:
![image](https://user-images.githubusercontent.com/7820865/87984566-8608cd00-cab0-11ea-8d0c-f75aab8a0032.png)

**Comment by socksy** [comment]
@ericdallo Thanks! That works for me too. Perhaps the readme should be updated to reflect that?

**Comment by ericdallo** [comment]
I'll open a PR for that later, thanks!
