### ISSUE TITLE
Please make this work with popular editors

### ISSUE THREAD

**Issue by divs1210** [snoe/clojure-lsp#16]
Hi!

I have a fear that LSP will become the de-facto standard for all languages, and Clojure/nREPL/CIDER will become an eccentric oddball - like lisp machines of yore.

I see this works with vim etc, but if it could work with popular editors like sublime/atom/vs code/etc. out of the box, it will be a great help to get more people onboard for Cojure.

I just tried sublime, and it said LSP doesn't support Clojure 😞, when it supports several niche languages out of the box.

I tried defining a custom client for it, and that didn't work either. 😞 

Please let me know how I can be of help.

*Help me, Obi Wan Kenobi, you're my only hope...*

**Comment by snoe** [comment]
@divs1210 

Different editors and plugins handle lsp clients in their own ways. vim, emacs, intellij seem to have single plugins that launch the lsp servers. These type of plugins should work out of the box with clojure-lsp

vs-code and atom (haven't looked at sublime) mainly seem to prefer single language plugins that need to be coded (as opposed to configured) to launch the language specific servers. This repository has a vs-code plugin that shows how that can be done in their architecture. 

So, to help with this, we need better documentation on how to configure other editors. Then for custom single-language plugins for other editors, we need to either create or support those client plugins to know about clojure-lsp.

A first step could be to figure out where the sublime ecosystem falls in here, it sounds from your description like it could be the first kind, but maybe the configuration for servers is hidden? In that case maybe they just don't know about us and you could raise an issue to add us to the list of languages.

(The REPL still has a very prominent place in my workflow but I think lsp is better positioned to do static transformations and queries of the code)

**Comment by divs1210** [comment]
> vim, emacs, intellij seem to have single plugins that launch the lsp servers. These type of plugins should work out of the box with clojure-lsp.
[lsp-mode for emacs](https://github.com/emacs-lsp/lsp-mode) doens't seem to support Clojure either.

**Comment by snoe** [comment]
@divs1210 Thanks to @dpsutton there are now instructions on how you can run clojure-lsp through emacs.  https://github.com/snoe/clojure-lsp#emacs

For sublime, if there are specific things that we can do with this plugin let's raise issues, or if you're still having troubles reach out to me on clojurians slack @snoe
