### ISSUE TITLE
Support standalone kondo config file

### ISSUE THREAD

**Issue by snoe** [snoe/clojure-lsp#168]
If a project already has kondo configuration for cli usage set, lsp should be able to pick it up from the project-path.

**Comment by snoe** [comment]
I wonder if you'd like to take this on @Cnly while it's still fresh? I won't be able to tackle it for awhile.

**Comment by ericdallo** [comment]
It should just check for a kondo config file in the project dir and merge with the lsp "clj-kondo" settings, right?

BTW I think this already works: https://clojurians.slack.com/archives/CPABC1H61/p1596720879059400

**Comment by snoe** [comment]
Fixed by afd7380f7f030c511d4c05dedd6bebdf367adb9c

The issue was, depending on how clojure-lsp is launched the project dir might not be the same as config-dir
