### ISSUE TITLE
Emacs Eglot support

### ISSUE THREAD

**Issue by arturovm** [snoe/clojure-lsp#174]
Hi @snoe. First of all, thanks a lot for your work! This has become an invaluable part of my workflow.

Having said that, I tried to use this with Eglot in Emacs, instead of with lsp-mode, and apparently Eglot is waiting for something to happen that `clojure-lsp` isn't doing? Eglot times out after a while. I don't know the cause exactly, as I don't have much experience debugging elisp packages.

I'd really appreciate a few pointers on this or, if suitable, I could try to help implement this, but I'd need some help getting familiar with the project 😛 

Thanks!

**Comment by ericdallo** [comment]
I don't think is a bug on clojure-lsp, probably some missing config on eglot for connecting with clojure-lsp, I use lsp-mode so I don't know much about eglot, but I bet that there is some debugging/logging config on eglot that could help debugging this

**Comment by arturovm** [comment]
@ericdallo You know what? I just dug around a little, and it turns out I just had to bump up the timeout timer for Eglot 🤦 Closing this issue now. Thanks for the reply!
