### ISSUE TITLE
How to exclude paths from being scanned

### ISSUE THREAD

**Issue by gdanov** [snoe/clojure-lsp#185]
I have clojurescript project (using deps.edn in case this matters).
 When searching for reference of a symbol I get results from my ./out/... folders. How do I specify in the .lsp/config.edn where to (not) look?

**Comment by ericdallo** [comment]
I think this is responsibility of your LSP client (emacs, vim, etc), if you use emacs and using `lsp-file-watchers`, you can add a denylist to that: https://emacs-lsp.github.io/lsp-mode/page/performance/#ignore-watch-foldersfiles

**Comment by gdanov** [comment]
Thank you. As someone coming from Cider (yes, on Emacs) I'm confused about how clojure-lsp learns  about my project — does it have  any understanding of my project by integrating with projectile (via the LSP client I guess) or deps.edn?

**Comment by ericdallo** [comment]
LSP is divided by the server (in this case `clojure-lsp`) and the client (in your case `lsp-mode`). `lsp-mode` guess the project root using projectile(take a look [here](https://emacs-lsp.github.io/lsp-mode/page/settings/) for more info, search for `lsp-auto-guess-root`), so the client just send the file contents to the server to server manage that.

If you want to know more about this LSP world, check [here](https://microsoft.github.io/language-server-protocol/overviews/lsp/overview/).

Also, I intend to write a [LSP tutorial](https://emacs-lsp.github.io/lsp-mode/tutorials/CPP-guide/) on how to work with CIDER and LSP together :)

**Comment by gdanov** [comment]
Thanks. Judging from my initial experience with clojure-lsp, cider would be interesting for me only for the REPL...
