### ISSUE TITLE
Cannot figure out the correct macro-def for specify!

### ISSUE THREAD

**Issue by gdanov** [snoe/clojure-lsp#187]
Looking at the code [here](https://github.com/snoe/clojure-lsp/blob/68676e4bc1d4e97a46ad6957ff12d6d1233857d8/src/clojure_lsp/parser.clj#L777)

I figured out the following configuration in  `<project-root>/.lsp/config.edn` should work, but it  doesn't

```
 :macro-defs {cljs.core/specify! [:element {:element :class-and-methods}]}
```

bellow is the feedback I get

<img width="1017" alt="Screenshot 2020-09-29 at 11 14 56" src="https://user-images.githubusercontent.com/957113/94539264-4ba47480-0245-11eb-8186-2463d35add4b.png">

**Comment by gdanov** [comment]
did some further digging:
* wrote test that passes such code to `find-usages` and making sure the output is meaningful — validated the definition  above is good
* via repl verified that `(get-in @db/db [:settings :macro-defs])` contains my custom def

what else could I do to debug the issue? it looks like I'm doing what I have to do but still the form is not properly recognized.

**Comment by ericdallo** [comment]
on your project, make sure your config is loading the `macro-defs` via `lsp-clojure-server-info`

**Comment by gdanov** [comment]
this is what I see, is it a problem  that the defs  are visible in the server, but NOT in the client section? 
```
 :project-settings
 {:project-specs
  [{:project-path "deps.edn", :classpath-cmd ["clj" "-Spath"]}],
  :source-paths ["src"],
  :macro-defs
  {'cljs.core/specify! [:element {:element :class-and-methods}],
   cljs.core/specify! [:element {:element :class-and-methods}],
   "cljs.core/specify!" [:element {:element :class-and-methods}]},
  :ignore-classpath-directories true},
 :client-settings
 {:dependency-scheme "jar",
  :source-paths #{"src" "test"},
  :macro-defs {},
  :project-specs nil,
  :cljfmt {:indents {}}},
```

**Comment by gdanov** [comment]
created custom lsp client, managed to pass the macro-defs, now the result looks like this:
```
LSP :: {:project-root
 "file:///Users/gdanov/work/playground/aoeuaoeu/aoeuaoe",
 :project-settings {},
 :client-settings
 {:dependency-scheme "jar",
  :macro-defs
  {cljs.core/specify! [:element {:element :class-and-methods}]},
  :source-paths #{"src" "test"},
  :project-specs nil,
  :cljfmt {:indents {}}},
 :port 61998}
```
:project-settings are empty on purpose.
I keep getting errors and the message log shows they come from kondo actually... one example
```
   {
      "message": "shared.cg/-dispose is called with 4 args but expects 1",
      "source": "clj-kondo",
      "code": "invalid-arity",
      "severity": 1,
      "range": {
        "end": {
          "character": 9,
          "line": 217
        },
        "start": {
          "character": 9,
          "line": 217
        }
      }
    }
```

**Comment by gdanov** [comment]
tried setting up linter exclusion (via .lsp/config.edn), because I can't figure out how to format it in elisp, but no effect
```
:project-settings
 {:clj-kondo
  {:linters {:invalid-arity {:skip-args [cljs.core/specify!]}}}}
```

**Comment by ericdallo** [comment]
We are using the macro-defs of clojure-lsp but we migrating to clj-kondo, so for now, you need to configure your macro for clj-kondo too.
I recommend you take a look on how to do that on clj-kondo readme

**Comment by gdanov** [comment]
Thanks for the support
