### ISSUE TITLE
Renaming keywords adds extra colons

### ISSUE THREAD

**Issue by snoe** [snoe/clojure-lsp#19]
Renaming `:foo` to `:bar` will actually rename it to `::bar` and renaming `::foo` to `::bar` will rename it to `::::bar`

**Comment by markx** [comment]
I took a look at the code. The extra `:` is from `u-prefix`. But I don't know the right fix. Is the problem in `ident-split`, or should we just not include prefix when there's no `u-ns`?

**Comment by markx** [comment]
Mentioned in the doc https://clojure.org/reference/data_structures#Keywords,
> The leading ':' is not part of the namespace or name.

So technically, when you rename a keyword like `:foo` to `:bar`, you are supposed to type "bar" instead of ":bar", which will not be a problem.
