### ISSUE TITLE
Duplicate diagnostics for unused private vars

### ISSUE THREAD

**Issue by bpringe** [snoe/clojure-lsp#199]
I'm seeing duplicate diagnostics in the `textDocument/publishDiagnostics` notification, one from clojure-lsp and one from clj-kondo, for unused private vars

From clojure-lsp
```json
        {
            "range": {
                "start": {
                    "line": 13,
                    "character": 7
                },
                "end": {
                    "line": 13,
                    "character": 15
                }
            },
            "severity": 2,
            "code": "unused",
            "message": "Unused declaration: get-type"
        }
```

From clj-kondo
```json
        {
            "range": {
                "start": {
                    "line": 13,
                    "character": 7
                },
                "end": {
                    "line": 13,
                    "character": 15
                }
            },
            "severity": 2,
            "code": "unused-private-var",
            "source": "clj-kondo",
            "message": "Unused private var core/get-type"
        }
```

I'm guessing the goal is to eventually only use clj-kondo for diagnostics?

**Comment by ericdallo** [comment]
Yes, we want to replace all clojure-lsp linters for clj-kondo, but currently clj-kondo works only for single files, not analyzing refenreces yet.
Still, I think we could fix this issue if we could remove only clj-kondo check for this lint.

**Comment by ericdallo** [comment]
@bpringe I just removed that clj-kondo linter since clojure-lsp already lint that along with public functions/vars.
We should remove it after #176 though

**Comment by bpringe** [comment]
Sounds good to me.
