### ISSUE TITLE
boot project support

### ISSUE THREAD

**Issue by snoe** [snoe/clojure-lsp#2]
Should be able to get the classpath from boot using `boot show --fake-classpath`

**Comment by patrickpichler** [comment]
Hi,

correct me if I'm wrong, but wouldn't it be enough to extend the [https://github.com/snoe/clojure-lsp/blob/f2c2fd8cd1737ce94e8e7e5e1420a3e55da161c2/src/clojure_lsp/handlers.clj#L154](determine-dependencies) functions to search for either a `build.boot` file, if no `project.clj` file exists in root folder? 

Furthermore the [https://github.com/snoe/clojure-lsp/blob/f2c2fd8cd1737ce94e8e7e5e1420a3e55da161c2/src/clojure_lsp/handlers.clj#L139](lookup-classpath) should execute the corresponding command to find the dependencies (either `lein classpath` or `boot show --fake-classpath`). 

If this is correct, I would like trying to implement it.

**Comment by snoe** [comment]
Yup, I think that's about it.

**Comment by patrickpichler** [comment]
I think this issue can be closed :+1:

**Comment by snoe** [comment]
Yup. Thanks for the work!
