### ISSUE TITLE
Find references doesn't work correctly when using both `:as` and `:refer` in ns require?

### ISSUE THREAD

**Issue by svdo** [snoe/clojure-lsp#205]
Thanks for Clojure-LSP, I think this is an awesome project of great value to the community!

I think I found an issue. I'm using a dev build of Calva with clojure-lsp integration. When I look at the references of a function, then I notice that a lot are not found. It seems that the issue is that we sometimes have require's of this form:

```
(ns ....
  (:require [my-ns.foo :as foo :refer [my-fn]))
```

In cases like these, it seems that clojure-lsp doesn't find the references of `my-fn` (without the `foo` alias).

**Comment by ericdallo** [comment]
@svdo if you just provide:
```clojure
  (:require [my-ns.foo :refer [my-fn]))
```

Does it works?

**Comment by svdo** [comment]
Yes indeed without the ns alias it does work.

**Comment by ericdallo** [comment]
@svdo Just tested and it seems to find correctly the references for my `c` ns:
![image](https://user-images.githubusercontent.com/7820865/102734549-db2a6280-431e-11eb-8be6-1e9ade4c2107.png)


Could you provide an example?

**Comment by svdo** [comment]
Hmm strange, I tried to reproduce just now but couldn't. Closing this issue. I'll reopen when I see it again. Thanks!
