### ISSUE TITLE
textDocument/documentSymbol response contains duplicates for cljc files

### ISSUE THREAD

**Issue by bpringe** [snoe/clojure-lsp#208]
Using clojure-lsp with Calva in VS Code, for some reason the client sends duplicate `codeLens/resolve` requests, so it receives duplicate responses. Also, the responses contain 1 more count of references than actually exist.

![image](https://user-images.githubusercontent.com/12722744/102655627-76f17e00-4127-11eb-90f8-30397141a137.png)

If I click one of those references to peek references, it shows only 1 reference in the peek window (which is correct). If I remove that reference to `hello`, the codeLens update to show 0 references (also correct). If any number of references above 0 is returned by lsp, the number is off by one, positively.

**Comment by bpringe** [comment]
The client sending duplicate requests seems more of an issue of VS Code, so I'll have to investigate this more. Could duplicate requests cause lsp to send an inaccurate references count?

**Comment by ericdallo** [comment]
This is really weird, it works pretty well using Emacs (client is [lsp-mode](https://emacs-lsp.github.io/lsp-mode/))
![image](https://user-images.githubusercontent.com/7820865/102658153-c484df80-4155-11eb-96f5-f9727900d0aa.png)

**Comment by bpringe** [comment]
I just realized that clojure-lsp is actually returning duplicates in the `textDocument/codeLens` response.

`textDocument/codeLens` request from client:

```json
{
  "textDocument": {
    "uri": "file:///home/brandon/development/simplefi/src/simplefi/data_transfer_specs.cljc"
  }
}
```

`textDocument/codeLens` response:

```json
[
  {
    "range": {
      "start": {
        "line": 0,
        "character": 4
      },
      "end": {
        "line": 0,
        "character": 32
      }
    },
    "data": [
      "file:///home/brandon/development/simplefi/src/simplefi/data_transfer_specs.cljc",
      1,
      5
    ]
  },
  {
    "range": {
      "start": {
        "line": 8,
        "character": 5
      },
      "end": {
        "line": 8,
        "character": 19
      }
    },
    "data": [
      "file:///home/brandon/development/simplefi/src/simplefi/data_transfer_specs.cljc",
      9,
      6
    ]
  },
  {
    "range": {
      "start": {
        "line": 35,
        "character": 5
      },
      "end": {
        "line": 35,
        "character": 29
      }
    },
    "data": [
      "file:///home/brandon/development/simplefi/src/simplefi/data_transfer_specs.cljc",
      36,
      6
    ]
  },
  {
    "range": {
      "start": {
        "line": 36,
        "character": 5
      },
      "end": {
        "line": 36,
        "character": 29
      }
    },
    "data": [
      "file:///home/brandon/development/simplefi/src/simplefi/data_transfer_specs.cljc",
      37,
      6
    ]
  },
  {
    "range": {
      "start": {
        "line": 0,
        "character": 4
      },
      "end": {
        "line": 0,
        "character": 32
      }
    },
    "data": [
      "file:///home/brandon/development/simplefi/src/simplefi/data_transfer_specs.cljc",
      1,
      5
    ]
  },
  {
    "range": {
      "start": {
        "line": 8,
        "character": 5
      },
      "end": {
        "line": 8,
        "character": 19
      }
    },
    "data": [
      "file:///home/brandon/development/simplefi/src/simplefi/data_transfer_specs.cljc",
      9,
      6
    ]
  },
  {
    "range": {
      "start": {
        "line": 35,
        "character": 5
      },
      "end": {
        "line": 35,
        "character": 29
      }
    },
    "data": [
      "file:///home/brandon/development/simplefi/src/simplefi/data_transfer_specs.cljc",
      36,
      6
    ]
  },
  {
    "range": {
      "start": {
        "line": 36,
        "character": 5
      },
      "end": {
        "line": 36,
        "character": 29
      }
    },
    "data": [
      "file:///home/brandon/development/simplefi/src/simplefi/data_transfer_specs.cljc",
      37,
      6
    ]
  }
]
```

Each one of the above are duplicated.

**Comment by ericdallo** [comment]
This doesn't happens with `lsp-mode`:
```json
[Trace - 05:43:21 PM] Sending request 'textDocument/codeLens - (285)'.
Params: {
  "textDocument": {
    "uri": "file:///home/greg/sample/src/sample/logic/a.clj"
  }
}


[Trace - 05:43:21 PM] Received response 'textDocument/codeLens - (285)' in 5ms.
Result: [
  {
    "range": {
      "start": {
        "line": 0,
        "character": 4
      },
      "end": {
        "line": 0,
        "character": 23
      }
    },
    "data": [
      "file:///home/greg/sample/src/sample/logic/a.clj",
      1,
      5
    ]
  },
  {
    "range": {
      "start": {
        "line": 2,
        "character": 5
      },
      "end": {
        "line": 2,
        "character": 10
      }
    },
    "data": [
      "file:///home/greg/sample/src/sample/logic/a.clj",
      3,
      6
    ]
  }
]
```

I can't see how differents clients can have differents results though

**Comment by bpringe** [comment]
Yeah, really odd. It seems maybe somehow duplicates are placed into the lsp db at some point. I see usages are pulled from `[:file-envs doc-id]` in the db .

https://github.com/snoe/clojure-lsp/blob/71ff703e747b2c4ddcdacbd9a4d5bf2aaa3a2c88/src/clojure_lsp/handlers.clj#L646

So maybe something weird is happening earlier since initialization that is causing duplicates in the db. I'll investigate the earlier messages.

**Comment by bpringe** [comment]
Ok, I used a small cljc sample file to make reading this stuff easier, and I noticed the first place I see duplication is in the `textDocument/documentSymbol` response.

The file

```clojure
(ns sample)

(def hello 1)

(comment
  hello)
```

`textDocument/documentSymbol` request to server

```json
{
  "textDocument": {
    "uri": "file:///home/brandon/development/clojure-test/src/sample.cljc"
  }
}
```

`textDocument/documentSymbol` response from server

```json
[
  {
    "name": "sample",
    "kind": 3,
    "range": {
      "start": {
        "line": 0,
        "character": 4
      },
      "end": {
        "line": 0,
        "character": 10
      }
    },
    "selectionRange": {
      "start": {
        "line": 0,
        "character": 4
      },
      "end": {
        "line": 0,
        "character": 10
      }
    },
    "children": [
      {
        "name": "hello",
        "kind": 13,
        "range": {
          "start": {
            "line": 2,
            "character": 5
          },
          "end": {
            "line": 2,
            "character": 10
          }
        },
        "selectionRange": {
          "start": {
            "line": 2,
            "character": 5
          },
          "end": {
            "line": 2,
            "character": 10
          }
        }
      },
      {
        "name": "hello",
        "kind": 13,
        "range": {
          "start": {
            "line": 2,
            "character": 5
          },
          "end": {
            "line": 2,
            "character": 10
          }
        },
        "selectionRange": {
          "start": {
            "line": 2,
            "character": 5
          },
          "end": {
            "line": 2,
            "character": 10
          }
        }
      }
    ]
  },
  {
    "name": "sample",
    "kind": 3,
    "range": {
      "start": {
        "line": 0,
        "character": 4
      },
      "end": {
        "line": 0,
        "character": 10
      }
    },
    "selectionRange": {
      "start": {
        "line": 0,
        "character": 4
      },
      "end": {
        "line": 0,
        "character": 10
      }
    },
    "children": [
      {
        "name": "hello",
        "kind": 13,
        "range": {
          "start": {
            "line": 2,
            "character": 5
          },
          "end": {
            "line": 2,
            "character": 10
          }
        },
        "selectionRange": {
          "start": {
            "line": 2,
            "character": 5
          },
          "end": {
            "line": 2,
            "character": 10
          }
        }
      },
      {
        "name": "hello",
        "kind": 13,
        "range": {
          "start": {
            "line": 2,
            "character": 5
          },
          "end": {
            "line": 2,
            "character": 10
          }
        },
        "selectionRange": {
          "start": {
            "line": 2,
            "character": 5
          },
          "end": {
            "line": 2,
            "character": 10
          }
        }
      }
    ]
  }
]
```

**Comment by bpringe** [comment]
So I guess from this point on the db has duplicates for that document, which causes the codeLens duplicates. No clue yet why this is happening though.

**Comment by ericdallo** [comment]
Could you try removing `.lsp/` folder where it contains the db and restart the server? 
Also you can take a look at `/tmp/lsp.out` to see if it logs anything useful

**Comment by bpringe** [comment]
The problem persists after removing the `.lsp` folder and restarting the server.

I'm not seeing anything useful in `/tmp/lsp.out`.

**Comment by ericdallo** [comment]
Is there any way where I could setup Calva with clojure-lsp to try to reproduce the issue?

**Comment by bpringe** [comment]
You can download this vsix: https://9023-125431277-gh.circle-artifacts.com/0/tmp/artifacts/calva-2.0.135-feat-lsp-client-3166a539.vsix

Then in VS Code install the vsix by going to Extensions (side menu) -> Click the `...` menu -> Click "Install from VSIX..." (Not sure how familiar you are with VS Code so just gave the UI directions.)

**Comment by bpringe** [comment]
For some reason that downloaded as a .zip for me this time (normally it's a .vsix IIRC), but if it does that for you just rename it to .vsix.

**Comment by bpringe** [comment]
So, I just noticed that rename does not work in cljc files either (only cljc), and this seems related to this issue, because I noticed the `textDocument/rename` response contains duplicate edits. I get an error: `Rename failed to apply edits` - but if there are usages in clj or cljs files, those are renamed.

**Comment by bpringe** [comment]
Just to report more related info - I noticed the outline feature has duplicate symbols for cljc files too.

**Comment by ericdallo** [comment]
Just tested with your vsix and it seems to work fine :thinking: 
![image](https://user-images.githubusercontent.com/7820865/102723915-62a9ae80-42ea-11eb-90b8-3e58ab6586f5.png)

**Comment by ericdallo** [comment]
Never mind, just found the output channel

**Comment by ericdallo** [comment]
Log
```javascript
[Trace - 5:49:27 PM] Sending request 'textDocument/codeLens - (137)'.
Params: {
    "textDocument": {
        "uri": "file:///home/greg/dev/clojure-sample/src/clojure_sample/d.clj"
    }
}

[Trace - 5:49:27 PM] Received response 'textDocument/codeLens - (137)' in 15ms.
Result: [
    {
        "range": {
            "start": {
                "line": 0,
                "character": 4
            },
            "end": {
                "line": 0,
                "character": 20
            }
        },
        "data": [
            "file:///home/greg/dev/clojure-sample/src/clojure_sample/d.clj",
            1,
            5
        ]
    },
    {
        "range": {
            "start": {
                "line": 2,
                "character": 5
            },
            "end": {
                "line": 2,
                "character": 10
            }
        },
        "data": [
            "file:///home/greg/dev/clojure-sample/src/clojure_sample/d.clj",
            3,
            6
        ]
    }
]
```
Tested Sample project: https://github.com/ericdallo/clojure-sample/blob/master/src/clojure_sample/d.clj

**Comment by ericdallo** [comment]
Oh, sorry, now I see the issue is specific for when the file is `.cljc`, didn't pay attention to that, I could reproduce the issue indeed.

**Comment by ericdallo** [comment]
It seems to only happen on cljc files, tested with cljs and I managed to create a test reproducing the bug.
https://github.com/snoe/clojure-lsp/pull/211

I'll work on the fix now

**Comment by ericdallo** [comment]
[This code](https://github.com/snoe/clojure-lsp/blob/master/src/clojure_lsp/parser.clj#L1143-L1148) is generating the duplicated `usages`, but it's on purpose, it adds usages for `clj` and `cljs` since we don't know if the project using `clojure-lsp` is a cljs or not.
I'm not sure how to handle this, WDYT @snoe ?

**Comment by bpringe** [comment]
>This code is generating the duplicated usages

Would calling `distinct` on that be sufficient? I don't see how it could cause issues. If two are the same, they mean the same thing and should be used the same way by any client.

**Comment by ericdallo** [comment]
They are different by the file type, one is `clj` and other is `cljs`

**Comment by ericdallo** [comment]
With this code:
```clojure
(def hello 123) 
(comment hello)
```

For `clj` files those are the usages:
```clojure
[{:tags #{:norename}
  :argc 2
  :end-row 1
  :sym clojure.core/def
  :str def
  :file-type :clj
  :col 2
  :end-col 5
  :row 1}
 {:tags    #{:declare :public}
  :end-row 1
  :sym user/hello
  :str hello
  :file-type :clj
  :col 6
  :signatures nil
  :end-col 11
  :doc nil
  :row 1}
 {:tags #{:norename}
  :argc 1
  :end-row 1
  :sym clojure.core/comment
  :str comment
  :file-type :clj
  :col 18
  :end-col 25
  :row 1}
 {:row 1
  :end-row 1
  :col 26
  :end-col 31
  :file-type :clj
  :sym user/hello
  :str hello
  :argc nil}]
```

```clojure
[{:tags #{:norename}
  :argc 2
  :end-row 1
  :sym clojure.core/def
  :str def
  :file-type :clj
  :col 2
  :end-col 5
  :row 1}
 {:tags    #{:declare :public}
  :end-row 1
  :sym user/hello
  :str hello
  :file-type :clj
  :col 6
  :signatures nil
  :end-col 11
  :doc nil
  :row 1}
 {:tags #{:norename}
  :argc 1
  :end-row 1
  :sym clojure.core/comment
  :str comment
  :file-type :clj
  :col 18
  :end-col 25
  :row 1}
 {:row 1
  :end-row 1
  :col 26
  :end-col 31
  :file-type :clj
  :sym user/hello
  :str hello
  :argc nil}
 {:tags #{:norename}
  :argc 2
  :end-row 1
  :sym cljs.core/def
  :str def
  :file-type :cljs
  :col 2
  :end-col 5
  :row 1}
 {:tags    #{:declare :public}
  :end-row 1
  :sym user/hello
  :str hello
  :file-type :cljs
  :col 6
  :signatures nil
  :end-col 11
  :doc nil
  :row 1}
 {:tags #{:norename}
  :argc 1
  :end-row 1
  :sym cljs.core/comment
  :str comment
  :file-type :cljs
  :col 18
  :end-col 25
  :row 1}
 {:row 1
  :end-row 1
  :col 26
  :end-col 31
  :file-type :cljs
  :sym user/hello
  :str hello
  :argc nil}]
```

**Comment by bpringe** [comment]
I see. At some point higher up in the call stack though, things are transformed into a common form, regardless of file type (going by the response json), so I'm guessing there is some place (or places), where de-duplicating makes sense. I could be wrong though.

**Comment by bpringe** [comment]
Also, thanks for taking time to look into this @ericdallo :smiley:

**Comment by ericdallo** [comment]
Good point @bpringe, I'll debug more to check if I can find this place/s :)

**Comment by bpringe** [comment]
Just playing around to see what happens, I changed document-symbol to this:

```clojure
(defn document-symbol [doc-id]
  (let [file-envs (:file-envs @db/db)
        local-env (get file-envs doc-id)
        symbol-parent-map (->> local-env
                               (keep #(cond (:kind %) [% (:kind %)]
                                            (is-declaration? %) [% :declaration]
                                            :else nil))
                               (map file-env-entry->document-symbol)
                               (group-by :namespace))]
    (->> (symbol-parent-map nil)
         (map (fn [e]
                (if-let [children (distinct (symbol-parent-map (:name e)))]
                  (assoc e :children children)
                  e)))
         (into [])
         distinct)))
```

and then the documentSymbol response did not contain duplicates. However, I realize other features are relying on the db for usages, so they will get duplicates (like code lens still showing duplicates), unless those responses were modified too.

Do you think the solution is simply to de-duplicate responses on the outer layer like this? Or is there an issue with how usages are stored in the db?

**Comment by ericdallo** [comment]
Nice!
That's exactly what I'm checking right now, if I don't find anything critical, we can think in de-deduplicate the callers/ use some common function to do that :)
Thanks for the debugging

**Comment by bpringe** [comment]
Do you have any advice for repl development with this project? I'm unfamiliar with how I could try out things at the repl to simulate what's happening when it's running on a project. So far I make a speculative change, then run `lein bin`, then copy the jar into Calva, which runs it on startup, but obviously this is a slow dev cycle.

**Comment by ericdallo** [comment]
I use Emacs with [cider](https://github.com/clojure-emacs/cider) which works perfect.
For this project, there are 3 options:
* test your function manually in the repl which most of time doesn't fit well since the functions have very dependencies, this is good for small functions
* Build the executable and test manually for big changes like you already do.
* Create a test for your case/fix which helps a lot debugging and most of time is what works to me

**Comment by ericdallo** [comment]
BTW, I have an idea that should work for the persisted usages in the DB, I'm working on it and probably will release a SNAPSHOT version for you to test, is that ok for you?

**Comment by bpringe** [comment]
Thanks, sorry, I deleted my comment asking about repl driven dev (for the record). I had just seen how the tests were set up regarding the db usage and started playing with them. Very helpful.

>is that ok for you?

Sounds great! Thanks a lot.

**Comment by bpringe** [comment]
While I don't know what your solution is or if it accounts for this issue, I found that if we dissoc `:file-type` from each usage in `reference-usages` then call `distinct` on the returned vector, it fixes the issue where resolved code lenses say twice as many references as they should for cljc files, and none of the tests break.

```clojure
(defn reference-usages [doc-id line column]
  (let [file-envs (:file-envs @db/db)
        local-env (get file-envs doc-id)
        {cursor-sym :sym} (find-reference-under-cursor line column local-env (shared/uri->file-type doc-id))]
    (log/warn "references" doc-id line column cursor-sym)
    (distinct
     (into []
           (for [[uri usages] (:file-envs @db/db)
                 {:keys [sym tags] :as usage} usages
                 :when (and (= sym cursor-sym)
                            (not (contains? tags :declare)))]
             {:uri uri
              :usage (dissoc usage :file-type)})))))
```

There probably should be tests added for code-lens-resolve for cljc files. If your change fixes this, please disregard, and if not I'd be happy to submit a PR with added tests.

**Comment by ericdallo** [comment]
This is a workaround since we are just fixing the wrong persisted usages, my idea is to fix the usages persisted in the db to not save "duplicated" usages, with that, it should fix every other place.

**Comment by ericdallo** [comment]
Still need to fix a test, but could you test it with this branch?
https://github.com/snoe/clojure-lsp/pull/211

**Comment by ericdallo** [comment]
Done here: https://github.com/snoe/clojure-lsp/pull/211
@bpringe could you test with calva and confirm this fix the issue?

**Comment by bpringe** [comment]
These changes fixed the issue(s)! :tada:

**Comment by ericdallo** [comment]
Finally... thanks for your help :)
I'll merge and release late today
