### ISSUE TITLE
Expand let bugs out in lamdas which take arguments

### ISSUE THREAD

**Issue by PEZ** [snoe/clojure-lsp#218]
If you run the `expand-let` refactor in an anonymous function that takes arguments, the function disappears, body and all. So with this code:

```clojure
(fn [foo]
  (let [state (create-state "# ")]
    (is (cell-alive? state [0 0]))
    (is-not (cell-alive? state [1 0]))
    (is-not (cell-alive? state [-10 -20]))))
```

Expanding the `let` gives you this:

```clojure
(let [state (create-state "# ")]
 [foo])
```

Whereas if the `fn` does not take arguments the let is correctly expanded, afaict.

**Comment by ericdallo** [comment]
Thanks for the report, fixed on latest release :)

**Comment by PEZ** [comment]
That was some quick turn-around! I can confirm the fix works. Thanks!
