### ISSUE TITLE
What unit does clojure-lsp use in lsp ranges

### ISSUE THREAD

**Issue by Avi-D-coder** [snoe/clojure-lsp#23]
Does this project use UTF-8, UTF-16, codepoint, or grapheme cluster indexes for lsp ranges?

I am conducting a [survey](https://github.com/Avi-D-coder/lsp-range-unit-survey) to inform the debate over what unit ranges should use in the [Language Server Protocol](https://github.com/Microsoft/language-server-protocol).
The debate is occuring in [issue #376](https://github.com/Microsoft/language-server-protocol/issues/376).

**Comment by snoe** [comment]
I'm not sure, I'm a couple libraries removed from parsing strings, but it looks like it's using java's PushbackReader https://docs.oracle.com/javase/6/docs/api/java/io/PushbackReader.html?is-external=true that reads ints. In that case I'm guessing it's UTF-16 ?

If you have a set of test bytes to run against I could check.

**Comment by snoe** [comment]
Here's some examples:

"noe\u0308l" => `{:start {:line 0, :character 0}, :end {:line 0, :character 5}}`
 "😸😾" => `{:start {:line 0, :character 0}, :end {:line 0, :character 4}}`
"👪" => `{:start {:line 0, :character 0}, :end {:line 0, :character 2}}`

**Comment by Avi-D-coder** [comment]
Is PushbackReader being used to read json messages or store the document's text?
A client that runs tests would be a good idea, but none exists. I'm not exactly sure how a test could be made for all languages?

As for the examples they are UTF-16.

**Comment by snoe** [comment]
The reader is being used to parse the text document values coming over the rpc channel. But by the time I get it it is a Java string as I used in the examples

**Comment by Avi-D-coder** [comment]
From the docs you linked it does not seem to be reading UTF-8. If it's not you will have issues with non ascii text, since RPC is always in UTF-8.

If your using Java strings to provide offsets you are currently spec compliant with UTF-16.

**Comment by snoe** [comment]
Thanks, I use the eclipse's lsp4j for handling the RPC, so I'm trusting they'll keep doing the right thing.
