### ISSUE TITLE
Definitions behind macros

### ISSUE THREAD

**Issue by jeaye** [snoe/clojure-lsp#24]
Hi! Thanks for the awesome project; I've just hooked clojure-lsp up with [coc.nvim](https://github.com/neoclide/coc.nvim) and I'm excited to see some things working. One issue I've noticed is that I can jump to the definition or find the references to a `defn`, but not a `defn` which was generated by a macro such as `defn-spec` ([docs for defn-spec](https://github.com/jeaye/orchestra#defn-spec)).

What's needed to support this?

**Comment by snoe** [comment]
I've pushed a new release with an initial stab at this problem.

In your clients' InitializationOptions you can set a "macro-defs" key, for something like `defn-spec`. You could probably define it like 

```json
{"macro-defs":
  {"defn-spec.core/defn-spec": [{"element": "declaration", "signature": ["next"]}, "element", "function-params-and-bodies"]}}
```

I'm still working out what optional elements will look like.

**Comment by jeaye** [comment]
Thanks for the quick reply. So, I take it that clojure-lsp isn't actually evaluating the macros? So every macro which defines things will need to be identified somehow? For example, `defn-spec` is the basis of all of my team's function definitions, but most of our functions are actually defined through macros (which either define re-frame event functions on the front-end or effect chains on the back-end). An example of an effect chain would be:

```clojure
(def-chain something
  ([_]
   {...})

  ([{:keys [...]}]
   {:commit ...}))
```

which compiles to the following:

```clojure
(defn-spec something#link-0
 [_]
 {...})

(defn-spec something#link-1
 [_]
 {:commit ...})

(defn-spec something
 [_]
 ...)
```

Each link in the chain ends up being a separate `defn-spec`. So, is there a way to map these macro expansions to multiple function definitions? Ideally such that I can jump to the definition of `something#link-1` and have it go somewhere near the right place?

**Comment by snoe** [comment]
That's correct, there's no expansion happening. 

In this case though I've found it quite rare in clojure to define macros that produce vars in this way (unhygienic might be the term?), so I'd be looking for a pr to support it. 

I'm going to reopen this tho to capture shortcomings in macro-defs.

**Comment by daveyarwood** [comment]
Hi @snoe, I'm really enjoying clojure-lsp so far!

I'm working on refining my `macro-defs` to reduce false positives. One thing I'm not sure about is whether it's possible to describe a macro where the invocation may or may not have a docstring, like `defn`?

The macro I'm trying to describe is `hoplon.core/defelem`. I've tried it these two ways:

```clojure
  hoplon.core/defelem
  [:declaration :params :bound-elements]
```

```clojure
  hoplon.core/defelem
  [{:element :declaration :doc? true} :params :bound-elements]
```

Both of which work when the docstring is left out, but don't capture the params correctly (I get an "Unknown symbol" error for each param) when a docstring is provided.

I could throw away the docstring part by capturing it as an `:element`, but then it wouldn't work in the case when the docstring is left out.

**Comment by daveyarwood** [comment]
It seems like it might be useful to be able to specify that an element is optional, e.g.

```clojure
[:declaration {:element :docstring :optional? true} :params :bound-elements]
```

**Comment by snoe** [comment]
@daveyarwood you can do optionality with `:pred`

`[{:element :declaration :doc? true} {:element :element :pred :string} :params :bound-elements]`

**Comment by daveyarwood** [comment]
I'm not sure I understand. Does `:pred :string` mean that the element is optional?

**Comment by snoe** [comment]
`defn-spec` from the op and `schema.core/defn` both have `params` and non-params interspersed. This isn't yet possible with macrodefs

**Comment by daveyarwood** [comment]
OK, gotcha. I could potentially work on a PR for that feature, if you'd like.

**Comment by snoe** [comment]
@daveyarwood `:pred :string` means that it will only parse the form in that position if it is a string, otherwise it will try to parse the form the with the next element in the macrodef.

**Comment by daveyarwood** [comment]
Aha - that did the trick. Thanks!

**Comment by daveyarwood** [comment]
@snoe Is it possible to greedily consume elements that match a given type? 

Actually, [the macro I'm trying to describe](https://github.com/adzerk-oss/env#get) is even more complicated than that... its arguments are pairs of declaration and value. For example, a call might look like:

```clojure
(env/def
  FOO :required
  BAR nil
  BAZ "some default value")
```

which defines `FOO`, `BAR`, and `BAZ`. Is there a way to account for this in my clojure-lsp config? If not, do you have thoughts on what the API should look like?

**Comment by snoe** [comment]
@daveyarwood a macro-def of `[{:element [:declaration :element] :repeat true}]` should do it for env/def

**Comment by daveyarwood** [comment]
That worked like a charm, thanks!

**Comment by lucasdf** [comment]
it would be really awesome to have support for properly declaring `schema.core/defn`.

**Comment by ericdallo** [comment]
@lucasdf we now have support for `schema.core/defn` :) it's working for almost a year I think.

Closing this since we now use `clj-kondo` which helps finding the macros
