### ISSUE TITLE
VSCode - how to configure project-root and src-paths?

### ISSUE THREAD

**Issue by scotts777** [snoe/clojure-lsp#34]
First, thanks so much for all the work on this lsp server.  I have the VSCode client running and starting the server just fine, but I can't see where to set the project-root and src-paths.  I tried this in the extensions.ts file

`let serverOptions = {
		run: {
			command: "clojure-lsp.dms",
			initializationOptions: {
				"source-paths": ["cljsrc"],
				"project-root": "/Users/scott/Projects/Clojure"
			}
		}`

I am trying to have a Workspace that points to that "Clojure" folder.  In that folder are some Deps projects that all have a source folder named "cljsrc".   I would want all those cljsrc folder to be indexed.  Any help would be very much appreciated.

thanks

**Comment by snoe** [comment]
I think you would have to set a source-path for each deps folder: `["dep1/cljsrc", "dep2/cljsrc"]`

I'd happily accept a patch to support globbing patterns in source-paths tho so you could do `*/cljsrc'

**Comment by snoe** [comment]
@scotts777 let me know if that worked for you or if there's more I can do.

**Comment by scotts777** [comment]
Thanks Case.  Yes that's was what I needed to do.
