### ISSUE TITLE
Support boot file different from build.boot

### ISSUE THREAD

**Issue by patrickpichler** [snoe/clojure-lsp#35]
With boot you can specify the name of the boot file via the `BOOT_FILE` env variable. Right now clojure-lsp only suports boot projects where the build file is named `build.boot`.

**Comment by snoe** [comment]
Would this work as a setting? I think having access to the env var would depend on how clients launch the server. 

Lein can also specify project files with -f (iirc)

**Comment by patrickpichler** [comment]
I'm no expert in boot, but from what I've read on the man pages the only way is via an env variable. 

Would it maybe help to add something like a `.lsp.conf` file or so to configure such things? I'm not sure if there are maybe other usecases for it as well. If not then it might be better to only support the default `build.boot` file.

**Comment by snoe** [comment]
I think a project specific file would be helpful in general - things now in client-settings like `macro-defs` and `cljfmt` rules are more likely than not to be project specific. It would also be helpful to be able to share the config with teammates.

An `.lsp/config.edn` would be useful and we could search up to the root of the file tree from project-root.

For this specifically, how about a setting like?

```clojure
{:project-specs 
  [{:project-path "build.boot" :classpath-cmd ["boot" "show" "--fake-classpath"]}
   {:project-path "other.boot" :classpath-cmd ["boot" "show" "--fake-classpath"] :env {"BOOT_FILE" "other.boot"}]}
```

**Comment by patrickpichler** [comment]
That sounds good :+1:
