### ISSUE TITLE
Bump lsp4j dependency version

### ISSUE THREAD

**Issue by ggilmore** [snoe/clojure-lsp#4]
I'm trying to use your language server, but I'm running into an issue where all the jsonrpc ID's for the responses sent to my client's requests are strings even if I sent an integer. 

For example, if I sent a request with `{"id": 1}`, I'd get a response back with `{"id": "1"}`. [This is a specification violation](http://www.jsonrpc.org/specification#response_object) that prevents my client from being able to match that response back to its request. 

I dug into this, and it seems like this has been fixed in the `lsp4j` library: https://github.com/eclipse/lsp4j/pull/155

However, the `0.3.0` version that you are using for `lsp4j` wouldn't include this fix. The [`0.3.1` version that they just released](https://github.com/eclipse/lsp4j/releases/tag/v0.3.1) should though. Could you try bumping the version that you use in this project?

**Comment by ggilmore** [comment]
Actually, my bad. `0.3.1` doesn't include this fix, but their `0.4.x` https://github.com/eclipse/lsp4j/releases/tag/v0.4.0.M6 releases should. Could try updating when you feel comfortable with doing so?

**Comment by snoe** [comment]
Closed by 7ef702fa38cffbec6122c0bc9726a5d37ea67cd2
