### ISSUE TITLE
goto definition and find references do not work for protocol methods

### ISSUE THREAD

**Issue by ProjectFrank** [snoe/clojure-lsp#42]
It would be really great if, for a given protocol method, find references showed:
- invocations of the protocol method
- implementations of the protocol method
- the protocol declaration itself

Ideally goto definition would take you to the implementation of the protocol method, but that's probably really hard or impossible. IMO, it would be acceptable to be taken to the protocol declaration.

**Comment by snoe** [comment]
LSP has [‘textDocument/implementation’](https://microsoft.github.io/language-server-protocol/specification#textDocument_implementation) for getting a list/going to implementations, if that's desired functionality could you raise a different issue for it? 

The rest should be doable though.
