### ISSUE TITLE
expand-let inserts error

### ISSUE THREAD

**Issue by lxsli** [snoe/clojure-lsp#50]
If I run `crel` on `(eutils/from-command...)`:

```
(defmethod auto-alloc :start
  (let [errfn #(sutils/->failure-result
                command %
                (eutils/from-command
                 command
                 (assoc allocatable
                        ::event/action ::allocation/unsuccessful)))]))
```

It goes bananas:

```
(defmethod auto-alloc :start
  (let [errfn (let command
               ^{:row 58, :col 15, :end-row 63, :end-col 68} #rewrite_clj.node.fn.FnNode{:children (<token: sutils/->failure-result> <newline: "\n"> <whitespace: "                "> <token: command> <whitespace: " "> <token: %> <newline: "\n"> <whitespace: "                "> <list:)})])
  (assoc allocatable
                          ::event/action ::allocation/unsuccessful))
>
```

I remember now that this is not what `crel` is for and yet, I would prefer it did nothing at all.

**Comment by snoe** [comment]
This seems to be from using `expand-let` inside a function literal. The nature of using rewrite-clj suggests that other refactorings inside function literals could be problematic. 

However, in testing it seems like there's a number of problems with the refactoring if you aren't positioned perfectly around the let.
