### ISSUE TITLE
Error renaming with coc.vim

### ISSUE THREAD

**Issue by erez-rabih** [snoe/clojure-lsp#55]
I'm receiving a 
```
[coc.nvim] Error on applyEdits: Error: Create document XXXXXXXXXXXXXXXXXXXX timeout after 1s.
```
error trying to rename
Is that a clojure-lsp bug or coc.vim?

**Comment by snoe** [comment]
Hard to say, you can [check the logs](https://github.com/snoe/clojure-lsp/blob/master/docs/troubleshooting.md#check-the-logs) when it happens. If there's no error there, I'd run through the coc.nvim troubleshooting

**Comment by erez-rabih** [comment]
it actually seems like a coc timeout when renaming multiple buffers.
coc author has replied that this should be optimized in future versions.
thanks for the help.

**Comment by l-qing** [comment]
# I found a solution for this problem:
<b>Pre-open all files containing keywords.</b>

It's not perfect but it works.
<hr>

# If you are already in vim, you can do this.
## 1. Use grep/Grepper to find all keywords and load into QuickFix.
## 2. Opens all the files in the quickfix list for editing.
```
    " FROM: https://gist.github.com/larsthegeek/4063239
    " quickfixopenall.vim
    "Author:
    "   Tim Dahlin
    "
    "Description:
    "   Opens all the files in the quickfix list for editing.
    "
    "Usage:
    "   1. Perform a vimgrep search
    "       :vimgrep /def/ *.rb
    "   2. Issue QuickFixOpenAll command
    "       :QuickFixOpenAll

    function!   QuickFixOpenAll()
        if empty(getqflist())
            return
        endif
        let s:prev_val = ""
        for d in getqflist()
            let s:curr_val = bufname(d.bufnr)
            if (s:curr_val != s:prev_val)
                exec "edit " . s:curr_val
            endif
            let s:prev_val = s:curr_val
        endfor
    endfunction

    command! QuickFixOpenAll         call QuickFixOpenAll()
```
## 3. Trigger shortcut key.
```
" Remap for rename current word
 nmap <leader>rn <Plug>(coc-rename)
```

<hr>

# If you are not in vim, you can do this.
## 1. Open all files in vim.
```
$ grep -wlr keywords * | xargs -o vi
# or
$ rg -wl keywords | xargs -o vi
```
## 2. Load files in buffer.
```
:bufdo 1
```
## 3. Trigger shortcut key.
