### ISSUE TITLE
Using ancient db-spec format

### ISSUE THREAD

**Issue by seancorfield** [snoe/clojure-lsp#57]
https://github.com/snoe/clojure-lsp/blob/32320822d956a73c4af5890b1a7de03b79eae864/src/clojure_lsp/db.clj#L15-L18

Using subprotocol/subname is consider legacy in `clojure.java.jdbc` and is not supported in `next.jdbc`. The code should use `:dbtype "sqlite"` and `:dbname` with the path to the DB file.

**Comment by snoe** [comment]
This is going to require getting off funcool.jdbc, which should be easy but might as well wait until next.jdbc or whatever becomes more standard or we using more db functionality.

**Comment by snoe** [comment]
Closed by https://github.com/snoe/clojure-lsp/commit/ef37e7e11154d688c96c2a7ad27c9d4a5b584c03

**Comment by seancorfield** [comment]
Thank you!

**Comment by dpsutton** [comment]
thank you @seancorfield !
