### ISSUE TITLE
Starting lsp server from REPL throws

### ISSUE THREAD

**Issue by roman01la** [snoe/clojure-lsp#58]
Starting server from REPL errors with `CompilerException java.lang.SecurityException: class "org.eclipse.lsp4j.TextDocumentIdentifier"'s signer information does not match signer information of other classes in the same package, compiling:(clojure_lsp/interop.clj:1:1)`, not sure how to solve this, but really want to be able to play with the project from REPL. Looking forward to contribute.

**Comment by roman01la** [comment]
nevermind, I figured it

**Comment by markx** [comment]
How did you fix this?
