### ISSUE TITLE
Jump from definition to usage

### ISSUE THREAD

**Issue by roman01la** [snoe/clojure-lsp#61]
Cursive has this very nice feature to be able to jump from definition to usage place. Is it possible to implement this? Happy to help, but need initial guidance.

**Comment by snoe** [comment]
Depends what you mean, LSP has a [references](https://github.com/snoe/clojure-lsp/blob/5903f624422923f4a43426b23463ec4c1335802b/src/clojure_lsp/main.clj#L105-L118) call which we implement that will show you everywhere a symbol is used, and it works well for functions. 

There's also an `implementation` and a `typeDefinition` call which would be appropriate for `reify` etc... and `deftype` etc... Basically they would work the same as `references` above, find the symbol under the cursor, then loop trough db usages until you find other usages of that symbol -- I annotate different usages with the `:tags` key so you can find the definition that way too.

**Comment by PEZ** [comment]
Not sure I am following. In VS Code, the **Goto References** feature works, so seems this is already in place?

**Comment by ericdallo** [comment]
I think this already works, can we close that?

**Comment by ericdallo** [comment]
Closing it since we have no more info and this seems to already work via the `references` lsp method
