### ISSUE TITLE
diagnostics in (comment ...)

### ISSUE THREAD

**Issue by FongHou** [snoe/clojure-lsp#67]
Hello,

Great tool! I really like the real-time diagnostics. Though have one issue using (comment ...) for repl driven development, diagnostics errors clutter quickfix list too much while code are in flux there (strict diagnostics seems less useful as they are evaled in repl frequently anyway). I'm wondering whether diagnostics can be disabled, at the same time still have all other features available in (comment ...) section.

Thanks!

**Comment by snoe** [comment]
I can see how that would be helpful although in my workflow I do appreciate them, so this should probably be gated by a client flag.

**Comment by FongHou** [comment]
Yes, a flag in lsp client settings/initializationOptions would be fine. Thanks.

**Comment by FongHou** [comment]
require and def forms are the main source of false negative diagnostics within (comment..). If they are fixed, I do like to have them. Thanks!
 
```
(comment                                                                                                                                                                      
  (require '[clojure.pprint :refer [pprint]])  Unknown symbol: clojure.pprint
  (def state (atom {}))  Unused declaration: state
  (swap! state assoc :key :value)
  (pprint state)  Unknown symbol: pprint
)

```

**Comment by tolgraven** [comment]
Since #_ also leaves diagnostics on (which seems more an error than matter of taste to me) maybe an easy compromise would be just that?
Fix #_ to do proper skips, leave comment as it is.

**Comment by ericdallo** [comment]
This is fixed since now we use `clj-kondo` for diagnostics for most cases and `clj-kondo` already doesn't lint comment blocks :)
![image](https://user-images.githubusercontent.com/7820865/103144470-7a2cd100-4708-11eb-9a4b-2deb097cf4df.png)
