### ISSUE TITLE
Add the ability to show documentation

### ISSUE THREAD

**Issue by MarinPostma** [snoe/clojure-lsp#68]
hi  folks,

I've been using clojure-lsp with Vim through coc.vim for quite some time now, and a feature that really miss is the ability to display documentation. In my coc.vim configuration K is mapped to show me the doc, and in rust I get: 
![image](https://user-images.githubusercontent.com/28804882/65494218-ac6fd300-deb4-11e9-9466-02f591faafef.png)

That would be a really neat feature for clojure-lsp too

**Comment by snoe** [comment]
We support documentation on the `hover` command, I assume you're using `signatureHelp`. It's unclear to me which is more appropriate. Have you run into any guides as to how the information between the two should differ?

**Comment by MarinPostma** [comment]
vim actually calls `hover`: 

```vim
" Use K to show documentation in preview window
nnoremap <silent> K :call <SID>show_documentation()<CR>

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction
```
however it seems to only show the function's prototype:

![image](https://user-images.githubusercontent.com/28804882/66267036-ae2e8480-e82c-11e9-8b9a-756e68272db7.png)

**Comment by snoe** [comment]
@MarinPostma you might be on deps.edn? The new release builds support into the default project specs and might be why you don't see docs.

**Comment by MarinPostma** [comment]
@snoe I was using the [AUR package](https://aur.archlinux.org/packages/clojure-lsp-bin/) that seems outdated... I'm trying with the latest version now, but i have trouble making it work => https://github.com/snoe/clojure-lsp/issues/76

**Comment by agzam** [comment]
@MarinPostma I have the same problem on Mac, see #82

**Comment by ericdallo** [comment]
Closing this as it works on hover for a while now, let me know if any issues related to that
