### ISSUE TITLE
Support clj deps.edn git dependencies

### ISSUE THREAD

**Issue by patrickpichler** [snoe/clojure-lsp#73]
With clj deps.edn you have the possibility to add git repositories as dependencies. When running the `clj -Spath` command it will include the source folders defined by the git repositories `deps.edn` files (at least i guess that it is working that way. I did not find any documentation regarding this, but my experiments showed that it is that way). 

It seems like the lsp cannot handle non `.jar` files to provide features such as code completion, documentation and jump to source. 

In my opinion it would be really nice if the lsp could support classpath entries which are folders and not just `.jar` files.

**Comment by snoe** [comment]
Merged and released, thanks.
