### ISSUE TITLE
defn spec doesn't account for return value type hints

### ISSUE THREAD

**Issue by daveyarwood** [snoe/clojure-lsp#77]
Little known fact: you can type hint the return value of a function by placing the type hint before the arguments vector (ref: https://clojure.org/reference/java_interop#typehints). It looks like clojure-lsp does not account for this, and having the extra form before the args vector throws everything off.

Without the `^File` return value type hint:

![2019-10-16-125947_1175x365_scrot](https://user-images.githubusercontent.com/4909079/66941608-412da280-f015-11e9-9892-76bfa95057c4.png)

With the type hint:

![2019-10-16-125935_1180x406_scrot](https://user-images.githubusercontent.com/4909079/66941615-45f25680-f015-11e9-93e5-00665163b846.png)

**Comment by patrickpichler** [comment]
It seems like the issue is [here](https://github.com/snoe/clojure-lsp/blob/master/src/clojure_lsp/parser.clj#L514). When defining a function with the type hint, the parameter list has tag type `:meta` instead of `:vector` or `:list`.

**Comment by Luminiscental** [comment]
This issue should be fixed now, from #95.

**Comment by daveyarwood** [comment]
I can confirm that it's fixed. Looks like you've been adding a ton to clojure-lsp recently, @Luminiscental -- much appreciated!
