### ISSUE TITLE
Cursive style "resolve macros as"?

### ISSUE THREAD

**Issue by miorimmax** [snoe/clojure-lsp#8]
Hi,

I have been tinkering with clojure-lsp for a few days and it seems like a massive improvement over my current workflow (either using vim-fireplace or acid.nvim), but from time to time I find myself editing my local clone of this repo to add handlers for some macros we use on our projects, like prismatic schema's `s/defn`, pedestal's `defhandler`, midje's `facts` and so on.

I noticed you mentioned in the readme that this could be done via languageserver's client configuration and since I'm considering to give it a try on my spare time and implement it, I'd like to hear what are your thoughts/plans on this?

From what I have seen so far, LanguageClient-neovim already implements the client configuration per project (via `.vim/settings.json` in the project root), so it is only a matter of implementing it the server too.

My idea so far is:
- Make the server able to read from this config
- Update the parser to also use the symbol->handler map from config
- Extra: have a global configuration for things that are shared across projects (i.e. libraries, so the project settings would be its own macros).

Also, I have not tried using macroexpand to resolve macros yet, but I suppose that could also be something cool to have, for example:

```clojure
user=> (defmacro deff [f x body] `(defn ~f [~@x] ~body))
#'user/deff
user=> (first (macroexpand-1 '(deff twice [x] (* 2 x))))
clojure.core/defn
```

**Comment by snoe** [comment]
This is now supported through `macro-defs` , see InitializationOptions section of README.md.
