### ISSUE TITLE
add-missing-libspec

### ISSUE THREAD

**Issue by agzam** [snoe/clojure-lsp#81]
For some reason, in seemingly correctly configured project in Emacs, with installed `lsp-ui` and `lsp-ui-sideline-show-code-actions t` it shows "add-missing-libspec" for everything. Even when cursor at a namespace declaration block.
 
Running `lsp-execute-code-action` says: `No workspace could handle workspace/executeCommand`, same is for `lsp-ui-sideline-apply-code-actions`.

Can someone suggest what might be wrong?

**Comment by snoe** [comment]
Code actions have just not been worked on as much as they should have been. They are mostly static with the add-missing-lib-spec command now, but that is only valid when you have an un-required namespace on the var your cursor is over. However, it looks like there's a bug even in that specific instance.

If they are getting in your way, I'd take an initial patch that removes the `add-missing-libspec` command while this gets worked out.

```
ERROR clojure-lsp.main: #error {
 :cause class clojure.lang.PersistentList cannot be cast to class clojure.lang.Named (clojure.lang.PersistentList and clojure.lang.Named are in unnamed module of loader 'app')
 :via
 [{:type java.lang.ClassCastException
   :message class clojure.lang.PersistentList cannot be cast to class clojure.lang.Named (clojure.lang.PersistentList and clojure.lang.Named are in unnamed module of loader 'app')
   :at [clojure.core$namespace invokeStatic core.clj 1589]}]
 :trace
 [[clojure.core$namespace invokeStatic core.clj 1589]
  [clojure.core$namespace invoke core.clj 1589]
  [clojure_lsp.refactor.transform$add_missing_libspec invokeStatic transform.clj 320]
  [clojure_lsp.refactor.transform$add_missing_libspec invoke transform.clj 318]
  [clojure.lang.AFn applyToHelper AFn.java 156]
  [clojure.lang.AFn applyTo AFn.java 144]
  [clojure.lang.Var applyTo Var.java 702]
  [clojure.core$apply invokeStatic core.clj 661]
  [clojure.core$apply invoke core.clj 652]
  [clojure_lsp.handlers$refactor invokeStatic handlers.clj 327]
```

**Comment by snoe** [comment]
Disabled by 6f280b78
