### ISSUE TITLE
lsp-treemacs doesn't work (?)

### ISSUE THREAD

**Issue by agzam** [snoe/clojure-lsp#86]
Apparently `lsp-treemacs-symbols` function doesn't work with clojure-lsp, it says: "The active buffer cannot provide symbols information", is that something that can be fixed via configuration, or clojure-lsp doesn't support that yet? I'm curious what needs to be done, for this feature to work.

**Comment by snoe** [comment]
@patrickpichler Added https://github.com/snoe/clojure-lsp/pull/96 and https://github.com/snoe/clojure-lsp/pull/98 I'm guessing one of those should address that error. Let me know!
