### ISSUE TITLE
Support for schema.core macros

### ISSUE THREAD

**Issue by ericdallo** [snoe/clojure-lsp#87]
On the company where I work, we have hundreds of clojure micro-services that use [schema.core](https://github.com/plumatic/schema). I think `clojure-lsp` can help a lot, but without support for `schema`, we can't use it on emacs :/.

Currently there are functions that return a typed value and functions that doesn't, like below:
```clojure
(require 'schema.core)

(s/defn even? :- s/Bool
    [number :- s/Int]
    (...))

(s/defn create-account!
    [account :- s/Any]
    (...))
```

I tried build a `macro-def`, but its seems to ignore bound-elements and on `lsp-mode`, and `lsp-find-reference` can't find these declared functions too.

Is there any `macro-def` for theses cases?

Thanks for the awesome project!

**Comment by ericdallo** [comment]
@snoe any updates on that?

**Comment by snoe** [comment]
@ericdallo  Thanks for pinging me on this. Right now there is not a macro-def for ignoring/skipping things in a parameter list. Luckily my vacation starts today, and this is the major thing I want to add to clojure-lsp over the break.

**Comment by ericdallo** [comment]
@snoe Thank you very much, this LSP it's awesome and works very well, but at work, we have a deep dependency on `schema.core`, so without a support for this, we can't use `clojure-lsp` and depends only on other libs like `joker`, `clj-kondo` and others...

If you need some help, I'll be very happy to help you with that

**Comment by snoe** [comment]
Fixed by 616ba37

The core component here is the `:sub-elements` macro which dives into a binding vector and continually tries to apply `:match-patterns` until reaching the end of the binding vector or pattern no pattern matches.

So if you have a binding like
`[a :- A b c :- C]` 
The first pattern will consume `a :- A` (with a param `a`) the second pattern will consume `b` (with param `b`) and the first pattern will consume `c :- C` (with a param `c`)

This is the macro-def built into lsp but I'll leave it here if anyone find it useful as an example.
```
'schema.core/defn [{:element :declaration :signature [:vector] :doc? true}
                      {:element :element :pred :keyword}
                      {:element :element :pred :symbol}
                      {:element :element :pred :string}
                      {:element :element :pred :map}
                      {:element :sub-elements
                       :match-patterns [[:symbol :keyword :any] [:param :element :element]
                                        [:symbol] [:param]]}
                      :bound-elements]
```

**Comment by ericdallo** [comment]
Thank you so much @snoe!

 it works very well for the most cases, but it looks like the macro it's not beeing applied when the function return is a `collection`

![image](https://user-images.githubusercontent.com/7820865/71451381-2aad7100-2753-11ea-8281-69469617643e.png)

**Comment by snoe** [comment]
Ok, it looks like i'll have to move this `match-patterns` concept up to the top level of a macro-def.

**Comment by ericdallo** [comment]
@snoe 
Sorry for reply again, but i found another problem, it looks like the `:params` on the `macro-def` doesn't work on destructured parameters:

![image](https://user-images.githubusercontent.com/7820865/71537711-b44d7200-28fe-11ea-975a-82b532e05d04.png)

**Comment by snoe** [comment]
46d040d Fixes destructuring
