### ISSUE TITLE
Support for midje custom symbols

### ISSUE THREAD

**Issue by ericdallo** [snoe/clojure-lsp#92]
[Midje](https://github.com/marick/Midje) is famous test framework, that uses custom symbols inside their macros

`clojure-lsp` has support for custom macros, but there's some libs that have custom symbols inside a custom macro like `fact`, `facts` and `tabular` from `midje.sweet`:

`fact`
![image](https://user-images.githubusercontent.com/7820865/71302056-b73be600-2385-11ea-8043-96bcd57ae2cf.png)

`tabular`
![image](https://user-images.githubusercontent.com/7820865/71302110-4d700c00-2386-11ea-8c18-817703344204.png)

Is there some way to bypass this with `macro-defs`?

**Comment by snoe** [comment]
I think something like `'midge.sweet/fact [:element :element :_ :element]` should work for `fact`

`tabular` seems to bind and declare the `?` vars after they are used in the `fact`. This would require changing the macro-def parser into a two pass system (bind params then do everything else).

That's not impossible, but this would require someone who wants it to step up and do a pr.

**Comment by ericdallo** [comment]
Got it, I tested the `fact` macro above, and didn't work :disappointed: 

I tried with and without namespace `require`:

`lsp/config.edn`
![image](https://user-images.githubusercontent.com/7820865/71451503-0dc66d00-2756-11ea-90bb-114d90ec926b.png)

_with namespace_
![image](https://user-images.githubusercontent.com/7820865/71451510-5a11ad00-2756-11ea-98f6-4ac4aedfb6f9.png)

_without namespace_
![image](https://user-images.githubusercontent.com/7820865/71451511-6d247d00-2756-11ea-8e07-d5b67761fbdb.png)

the `refer :all` on `midje.sweet` is pretty common, maybe this would be another issue.

**Comment by ericdallo** [comment]
Thank you very much :D

**Comment by oryband** [comment]
This doesn't work by default in coc.nvim. Can someone please provide an explanation on how to apply this on a coc.nvim coc-settings.json?

**Comment by ericdallo** [comment]
I think @snoe use vim, maybe he could help with these settings

**Comment by oryband** [comment]
This is what I get for using `tabular ?x ?y` and `=>` signs.

![image](https://user-images.githubusercontent.com/115387/94361234-84184700-00bb-11eb-82b8-e9f72f32d75a.png)
![image](https://user-images.githubusercontent.com/115387/94361238-867aa100-00bb-11eb-9c3f-0a4db562d3ef.png)

And this is my `:CocConfig`:
```json
{
    "diagnostic.checkCurrentLine": true,
    "diagnostic.enableMessage": "jump",
    "diagnostic.enableHighlightLineNumber": false,

    "languageserver": {
        "clojure-lsp": {
            "command": "bash",
            "args": ["-c", "clojure-lsp"],
            "filetypes": ["clojure"],
            "rootPatterns": ["project.clj"],
            "additionalSchemes": ["jar", "zipfile"],
            "trace.server": "verbose",
            "initializationOptions": {
                "ignore-classpath-directories": true
            }
        }
    }
}
```
